### ISSUE TITLE
Could double discount be added?

### ISSUE THREAD

**Issue by sunscreem** [picandocodigo/efp_discount#3]
Could this possibly include double discount vouchers? Its really hard to know how they actually work on complex bills.

For example:

![image](https://user-images.githubusercontent.com/7523595/58763189-a3e33d80-854f-11e9-9bd6-607e0e63a7c4.png)

I've not idea how right or wrong this one was 😂

**Comment by picandocodigo** [comment]
I have no idea how Double Discount Vouchers work :laughing: 
To be honest, most of the discount logic came from Fakevox who has way more knowledge than me on this. But knowing how they work, it'd be easy enough to add them.

**Comment by sunscreem** [comment]
Cool - one for the todo list.
